# Encrypted secrets for mastodon-large. See the do-production sibling.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mastodon
resources:
  - mastodon-env-secret.sops.yaml
