apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-yaml
  namespace: mastodon
data:
  vector.yaml: |
    # Forwarding logs to Logs.betterstack.com
    # ---------------------------------------
    # Generated on 2024-08-16: https://logs.betterstack.com/vector-yaml/ubuntu/5V359qtjL5knFe9cA9q2cV9W
    # Learn more about Vector configuration: https://vector.dev/docs/reference/configuration/

    data_dir: /vector-data-dir

    sources:

    transforms:

    sinks:
      
      better_stack_http_sink_5V359qtjL5knFe9cA9q2cV9W:
        type: "http"
        method: "post"
        uri: "https://in.logs.betterstack.com/"
        encoding:
          codec: "json"
        auth:
          strategy: "bearer"
          token: "5V359qtjL5knFe9cA9q2cV9W"
        inputs: []

      better_stack_http_metrics_sink_5V359qtjL5knFe9cA9q2cV9W:
        type: "http"
        method: "post"
        uri: "https://in.logs.betterstack.com/metrics"
        encoding:
          codec: "json"
        auth:
          strategy: "bearer"
          token: "5V359qtjL5knFe9cA9q2cV9W"
        inputs: ["better_stack_apache_metrics_parser_5V359qtjL5knFe9cA9q2cV9W","better_stack_nginx_metrics_parser_5V359qtjL5knFe9cA9q2cV9W","better_stack_docker_metrics_parser_5V359qtjL5knFe9cA9q2cV9W","better_stack_host_metrics_5V359qtjL5knFe9cA9q2cV9W"]


    # --- end of 2024-08-16: https://logs.betterstack.com/vector-yaml/ubuntu/5V359qtjL5knFe9cA9q2cV9W
