##### This file is empty and only used for a reference on the public gh repo.

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mastodon-env-secret
#   labels:
#     app.kubernetes.io/name: mastodon
#     app.kubernetes.io/instance: mastodon
# data:
#   AWS_ACCESS_KEY_ID: 
#   AWS_SECRET_ACCESS_KEY: 
#   # This needs to exist as long as the pg server cert isn't trusted >_>
#   # https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain
#   # https://github.com/mastodon/mastodon/issues/23716
#   DB_SSLMODE: require
#   DEFAULT_LOCALE: en
#   ES_ENABLED: "true"
#   ES_PRESET: single_node_cluster
#   LIBRE_TRANSLATE_ENDPOINT: "http://libretranslate.mastodon:5000"
#   LOCAL_DOMAIN: masto.nyc
#   #ALTERNATE_DOMAINS: dev.masto.nyc # ONLY FOR
#   # https://devcenter.heroku.com/articles/tuning-glibc-memory-behavior
#   MALLOC_ARENA_MAX: "2"
#   NODE_ENV: "production"
#   NODE_TLS_REJECT_UNAUTHORIZED: "0"
#   OTP_SECRET: 
#   RAILS_ENV: "production"
#   S3_ALIAS_HOST: cdn.masto.nyc
#   S3_BUCKET: 
#   S3_ENABLED: 
#   S3_ENDPOINT: 
#   S3_PERMISSION: 
#   S3_PROTOCOL: 
#   # https://docs.joinmastodon.org/admin/optional/object-storage/#cloudflare-r2
#   S3_REGION: 
#   SECRET_KEY_BASE:
#   SKIP_POST_DEPLOYMENT_MIGRATIONS: 
#   SMTP_FROM_ADDRESS: notifications@masto.nyc
#   SMTP_LOGIN: 
#   SMTP_PASSWORD: 
#   SMTP_PORT: 
#   SMTP_SERVER: 
#   STREAMING_API_BASE_URL: "wss://streaming.masto.nyc"
#   STREAMING_CLUSTER_NUM: "1"
#   VAPID_PRIVATE_KEY: 
#   VAPID_PUBLIC_KEY: 