---
# Source: mastodon/templates/deployment-streaming.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbg
  namespace: mastodon
  labels:
    app: dbg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbg
  template:
    metadata:
      labels:
        app: dbg
    spec:
      priorityClassName: masto-low
      containers:
        - name: dbg
          image: nicolaka/netshoot@sha256:b09d9b21381f47a79b3cbcb30da25266dc17186ea00ae65e99fdc51396f48e70
          command:
            - /bin/bash
            - -c
            - --
          args:
            - while true; do sleep 30; done;
          ports:
            - name: streaming
              containerPort: 80
              protocol: TCP
