# Media cleanup
# We cleanup weekly, just like the default helm chart has set. There hasn't been
# much of a need to extend or shorten that so far.
---
# Source: mastodon/templates/cronjob-media-remove.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mastodon-media-remove
  labels:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/version: "v4.3.0"
spec:
  schedule: 0 5 14 * 0
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          name: mastodon-media-remove
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mastodon-media-remove
              image: "ghcr.io/mastodon/mastodon:v4.3.0"
              imagePullPolicy: IfNotPresent
              command:
                - bin/tootctl
                - media
                - remove
                - --prune-profiles
                - --days=365
                - --verbose
              envFrom:
              - configMapRef:
                  name: mastodon-env-secret
              - configMapRef:
                  name: mastodon-env-tf
