# Tags Updater
# We are affected by:
# https://github.com/mastodon/mastodon/issues/20230
# Soooooooo this has to exist.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: mastodon
spec:
  schedule: "30 1 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          name: postgres-backup
        spec:
          restartPolicy: Never
          containers:
            - name: postgres-backup
              image: eeshugerman/postgres-backup-s3:16
              command:
                - /bin/sh
                - -c
              args:
                - "chmod +x /run.sh && /run.sh && /postgres.sh"
              volumeMounts:
              - mountPath: /postgres.sh
                name: postgres-completion
                subPath: postgres.sh
              env:
                - name: BACKUP_KEEP_DAYS
                  value: "14"
                - name: S3_ENDPOINT
                  value: "https://nyc3.digitaloceanspaces.com/"
                - name: S3_PREFIX
                  value: "backups"
                - name: S3_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: DEFAULT_S3_REGION
                - name: S3_ACCESS_KEY_ID
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: DEFAULT_S3_KEY_ID
                - name: S3_SECRET_ACCESS_KEY
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: DEFAULT_S3_KEY_SECRET
                - name: S3_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: postgres_bucket
                - name: POSTGRES_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: masto-direct-db
                      key: postgres_host
                - name: POSTGRES_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: masto-direct-db
                      key: postgres_port
                - name: POSTGRES_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: masto-direct-db
                      key: postgres_db
                - name: POSTGRES_USER
                  valueFrom:
                    configMapKeyRef:
                      name: masto-direct-db
                      key: postgres_user
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      name: masto-direct-db
                      key: postgres_pass
              imagePullPolicy: IfNotPresent
          volumes:
          - name: postgres-completion
            configMap:
              name: postgres-completion
              defaultMode: 0755
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
