# Tags Updater
# We are affected by:
# https://github.com/mastodon/mastodon/issues/20230
# Soooooooo this has to exist.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: masto-indexup
  namespace: mastodon
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Allow
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          name: masto-indexup
        spec:
          containers:
            - name: masto-indexup
              image: ghcr.io/mastodon/mastodon:v4.3.0-beta.2
              command:
                - bin/tootctl
                - search
                - deploy
                #- --only=accounts
              envFrom:
                - configMapRef:
                    name: mastodon-env
                - secretRef:
                    name: mastodon
              envFrom:
              - configMapRef:
                  name: mastodon-env-secret
              - configMapRef:
                  name: mastodon-env-tf
              env: 
                - name: PORT
                  value: '3000'
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          #terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/part-of
                        operator: In
                        values:
                          - rails
                  topologyKey: kubernetes.io/hostname
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
