# Tags Updater
# We are affected by:
# https://github.com/mastodon/mastodon/issues/20230
# Soooooooo this has to exist.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: mastodon
spec:
  schedule: "30 1 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          name: postgres-backup
        spec:
          restartPolicy: Never
          containers:
            - name: postgres-backup
              image: eeshugerman/postgres-backup-s3:16
              env:
                - name: BACKUP_KEEP_DAYS
                  value: "14"
                - name: S3_ENDPOINT
                  value: "https://nyc3.digitaloceanspaces.com/"
                - name: S3_PREFIX
                  value: "backups"
                - name: S3_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: DEFAULT_S3_REGION
                - name: S3_ACCESS_KEY_ID
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: DEFAULT_S3_KEY_ID
                - name: S3_SECRET_ACCESS_KEY
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: DEFAULT_S3_KEY_SECRET
                - name: S3_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: postgres_bucket
                - name: POSTGRES_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: mastodon-env-tf
                      key: DB_HOST
                - name: POSTGRES_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: mastodon-env-tf
                      key: DB_PORT
                - name: POSTGRES_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: mastodon-env-tf
                      key: DB_NAME
                - name: POSTGRES_USER
                  valueFrom:
                    configMapKeyRef:
                      name: mastodon-env-tf
                      key: DB_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      name: mastodon-env-tf
                      key: DB_PASS
              imagePullPolicy: IfNotPresent
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
