apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-storage-backup
  namespace: mastodon
spec:
  schedule: "30 1 * * *"
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          name: postgres-storage-backup
        spec:
          volumes:
            - name: postgres-completion
              configMap:
                name: postgres-completion
                defaultMode: 0500
          containers:
            - name: postgres-storage-backup
              image: tiredofit/db-backup:4.1.3
              imagePullPolicy: IfNotPresent
              command:
                # - /etc/services.available/10-db-backup/run
                - /init
                - backup-now
              volumeMounts:
                - name: postgres-completion
                  mountPath: "/script"
              env:
                # - name: DEBUG_MODE
                #   value: "TRUE"
                - name: PGSSLMODE
                  value: "require"
                - name: MODE
                  value: "MANUAL"
                - name: MANUAL_RUN_FOREVER
                  value: "FALSE"
                - name: CONTAINER_ENABLE_SCHEDULING
                  value: "FALSE"
                - name: CONTAINER_ENABLE_MONITORING
                  value: "FALSE"
                - name: DEFAULT_POST_SCRIPT
                  value: "/script/postgres.sh"
                - name: DEFAULT_BACKUP_LOCATION
                  value: 'S3'
                - name: DEFAULT_S3_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: postgres_bucket
                - name: DEFAULT_S3_KEY_ID
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: DEFAULT_S3_KEY_ID
                - name: DEFAULT_S3_KEY_SECRET
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: DEFAULT_S3_KEY_SECRET
                - name: DEFAULT_S3_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: DEFAULT_S3_REGION
                - name: DEFAULT_S3_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: storage-backup
                      key: DEFAULT_S3_HOST
                - name: DB01_TYPE
                  value: "pgsql"
                - name: DB01_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: mastodon-env-tf
                      key: DB_HOST
                - name: DB01_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: mastodon-env-tf
                      key: DB_PORT
                - name: DB01_NAME 
                  valueFrom:
                    configMapKeyRef:
                      name: mastodon-env-tf
                      key: DB_NAME
                - name: DB01_USER
                  valueFrom:
                    configMapKeyRef:
                      name: mastodon-env-tf
                      key: DB_USER
                - name: DB01_PASS 
                  valueFrom:
                    configMapKeyRef:
                      name: mastodon-env-tf
                      key: DB_PASS
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
