apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-completion
    namespace: mastodon
data:
    postgres.sh: ENC[AES256_GCM,data:oW83cjCM55cJd9N5qoIV2AXUYLdnbfpleWV0tJuAw+/7gFi1AB/JO1RMmcvNG18z/2pqj5ltkhcyXDzrZ4XT1QnnBuYM6C6ieAlUMYZXedLdxWeqqlegSDkDEe4uTg38WJAo,iv:pIdjcRX02CupRBRfR5HCtftFU8dsEkK7PjTJUDibfDE=,tag:vZSJvaxDsWTBhppUC91agw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdm9XZEZYcjdYdDhFRjAv
            WXkzeWNCbFZCK3AyNGpLN2JQV3F0a0x3T0dJCmlzZTZUWldGWVBqZzZOcE5XS1oy
            MDFaay95NGUrY2NaWGNmN1V0TW9KT1kKLS0tIFdaNy8ydDJZZ1lhdlhmWlhNMDRH
            a0w4OUVmODdXbWt1dHZBMWVCK21FR00KKFf7TIsgAGYW+DpEd74YhuiZcfjbTYGW
            sX+F351Njmbq152IFy7awHw9acTBa78zzOK0XYfurdARFZvuIk9oCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qky2jy0fqdputaryf4s57jt8x8cnwrc4cxnuzrgggd8p5vxxhytqkt8g8s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T03:30:13Z"
    mac: ENC[AES256_GCM,data:hS4T2O1TVFgvsSdCW+u4FoWviqgcgp1K+Okh1tf8eQOY/Ay8K7IYFqHR5+3+v6fV8JtWlV8y7ERa9YbotSf+gzQ79q5lHVqvfeUpaBQHq66jpP7h8gS8rdvjk9HpjmdS28A+5ngRgUNDIrq9mYrLmQDghF084uAw5sv4vWvsytI=,iv:0BbZuODhBINrG8kVfviHZJrWnCv5AD1fhYP6iPGf51M=,tag:y98MdAcUxG1QxTORjJ9VEA==,type:str]
    version: 3.13.3
