# Source: mastodon/templates/configmap-env.yaml
apiVersion: v1
kind: Secret
metadata:
    namespace: mastodon
    name: storage-backup
    labels:
        app.kubernetes.io/name: mastodon
        app.kubernetes.io/instance: mastodon
type: Opaque
stringData:
    #ENC[AES256_GCM,data:u7zNWqEFI5nhRf4wJKZW2vziuZ7altPt5wvI,iv:cev19LFkbRtou6oTgOs5tP1TwU8e7jyE04KIITck2BY=,tag:lY72ycwPXrq63k6W3pC1Eg==,type:comment]
    DEFAULT_S3_KEY_ID: ENC[AES256_GCM,data:TTnIgAluPClbF/T8WFih1x6RMac=,iv:ywr2hImJZFVFWe8DzVs205yd/9Ez9AYZeNvm9vV+q1E=,tag:bd5XKapTgUdj9ClPDyV7Iw==,type:str]
    DEFAULT_S3_KEY_SECRET: ENC[AES256_GCM,data:21jd3urtNeSrvrxZu2RHTd87qQ0z8VaKkacic4xQOXhbdndqm9vooi387g==,iv:+3OXdxMGBB2aadNfz2XQraG/KNMObDNsoL7TVkQWgU0=,tag:mKpIco1LY5YmngsIrnr4Pw==,type:str]
    DEFAULT_S3_REGION: ENC[AES256_GCM,data:BqxZFg==,iv:9yDlKs9hYbH4plHJP2R7AE+ueWV0FVh/j3U5X7OMmQI=,tag:1A/Zibvo7vgPMva60XZzlw==,type:str]
    DEFAULT_S3_HOST: ENC[AES256_GCM,data:CBuX4BcT/UhqjM5uz5FrrsYfO2axHzIcUrtv1+UItXpeZi5y,iv:fUE63KIYBaBzXcZ5NNFdejw7qy/qOJCu3u60Oy1irMU=,tag:AuJo5XhWaQss8FG2FdQZoA==,type:str]
    postgres_bucket: ENC[AES256_GCM,data:tCMiciTtv8gDsTWuZYa5KeIVxvlE1rcY,iv:oqr5SXULKTKg0w1P4BVQ0em5YHV6lKgbC2h7DOeGJ4s=,tag:+CCT252kPyAkoxJdt3R8NA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWkUyODUyOGs2OEVYTGpz
            MWhDeGlLTXhpR043ekNnL3AzMDlCaVpTdjM4ClNQajZvQUMxUGRleDd4dXYxb2JD
            M2hxOGlEdUtUM1prelpQWEVyckgwMjQKLS0tIEVCRGkxbEdRV2p3NGtkc0tySDZQ
            VDMxeDc4dHlBbVd5WXlPY0wrdnNsWU0KeEhMiQm9hs1wmgHWVZGMYqJZEkjMi454
            XQ7R+Am96Mn6SdbaffR5qgTQLvi3+411m+NNJWkL7s2gyCQDqBj0xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qky2jy0fqdputaryf4s57jt8x8cnwrc4cxnuzrgggd8p5vxxhytqkt8g8s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T03:30:13Z"
    mac: ENC[AES256_GCM,data:Ebwn3ZVR3V1jBgYzlun25B90ODPsd4kwAw30cKwcUUQLIbjLoyzZnPf/T6/WjuUFh/ILXK42vumqSJnbQToGqaW2W2RkeJ2HvbsC3fuQ7ipBciV8oRBQON9gCqsupDFMT6VH63XXwsxMvFRMwZS884bMqamKm3bmLCVNcylXGY4=,iv:a+9xM92wlSrlikYlo9NXdFUhQyAdwRwmPkB+jFIiFTw=,tag:1g6fWro+SEeY7hdhkbL8FA==,type:str]
    version: 3.13.3
