apiVersion: v1
data:
    key: ENC[AES256_GCM,data:QYx3bar3oCfNOi01o5ZGme6jvnFJS25DhI7O7pN2bxq96l+2LjWsqbe3C4a17NgZv2Bk3EuM19i8cdsv,iv:dz5N8SRil+MIA/5RM1+4XgwSggGztf0pfECCi09TxTc=,tag:+tDKpZnAl5DhB2jwKjNfaQ==,type:str]
kind: Secret
metadata:
    labels:
        app.kubernetes.io/instance: mastodon
        app.kubernetes.io/name: sync-blocked-email-domains
    name: sync-blocked-email-domains
    namespace: mastodon
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSkhFU29SRlY0NWNZdm50
            Y1NIVTBmZHhHaTlZaXlENVFqN0YrY3phaUdZCmlNYmVib0ZRRWVBVktBeGQ3MHJn
            OXJHSHNuYm1QZlI5NVlaWUwyWklFLzQKLS0tIFEyL21teFVFZnJkd1pES2dpeXlU
            dnB0alUwTE9RYWhoLzNUWEUvVnYwTWMK4BYRSXP4HFCyG+Z2Dkkb9EwH/SdO8JpG
            ByxobhgtdVA3GXkxdJRr3qQa2DNI1ItgmS9CzmZpcPwVf1elp1XOdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qky2jy0fqdputaryf4s57jt8x8cnwrc4cxnuzrgggd8p5vxxhytqkt8g8s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T03:30:45Z"
    mac: ENC[AES256_GCM,data:rwIsP6DJuWeP4L3qjrI9bgP28eVOIrQMV1d7MCgtV9Kqdye5rQpN0tT7rtaS/Uk0vc1VVDlwTdIzBa0yuvF7Y4ZdYhfFWpmB6XUrk8TwWz3n0CM9NpszQg4RoODJMQsvz2hP9R2M54AcdBGtcl5Z/5FFpeFEffaiwin06Jqi2k8=,iv:F1yzS92nXx1oSIH4PfwMCdf0lEH3OkbDHmFEvyA26Gk=,tag:f9m0QWztfkvEL7a2C9JquA==,type:str]
    version: 3.13.3
