### This file contains private config values - DO NOT COMMIT TO GIT
### Copy from configmap-timeline-health-private.yaml and fill in real values
apiVersion: v1
kind: ConfigMap
metadata:
    name: timeline-health-config
    namespace: mastodon
data:
    HEARTBEAT_URL: ENC[AES256_GCM,data:mTPRHAyfVScP542kXZ8rfOctZYoiHtZXmrLDvpb1mruA708G++hjZHH12oRZGAEfX9FCr2koVBa1WM9hn3WeDGe7lmW80FnA,iv:M706Cc0NCktjL87WUhNOZtLh3uaDYZ8yioouqekkGfM=,tag:BtV0q83akFeBxQ73Mszg6w==,type:str]
    MASTODON_HOSTNAME: ENC[AES256_GCM,data:HJOu/O39YQuE,iv:8wXnOM1hex4WGu6uAJTRMXmexb5z9Pmtl1e7Hkc8K6k=,tag:X6K9jiK/dbU0D0UM4ZDKoQ==,type:str]
    FRESHNESS_THRESHOLD: ENC[AES256_GCM,data:VKQ=,iv:BMvPfcdJNkG1Kj/gP/7+hbm7G3B8UHaLCVqCnncRImc=,tag:1vXOBM5NMPZn26u2+7hBDQ==,type:str]
    SAMPLE_SIZE: ENC[AES256_GCM,data:iSk=,iv:AOgiMsHi87UG0Q20xI5ebbW2mahec8RA7ZRCQGkKYRw=,tag:40/rDs2hkGCJkBTPBnbJew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcTlZQlJpbmNtZlVtWTM4
            cG5QUXFiRE9zTUJ4VzJsT3BaTDFSSGxlWW5zCnVwa3ZRc3ZtYzJydCtqdWpGU2N4
            b1R4bndZTkUwWmpBbTEyalU5TW55d0kKLS0tIFZOc0d2eTVpSGFTNDJNcW5LK09X
            SGY5cHFNYXFmTnEybUxRclhDdmUyRHMKs5EtCc+2lVo4vpXQF+Bw1ynEhfAELvs/
            WjWUn6IHkrB9mZEb4VY15m7LCgynlueTv0BZleX4BcQmJA4z+nOlBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qky2jy0fqdputaryf4s57jt8x8cnwrc4cxnuzrgggd8p5vxxhytqkt8g8s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T03:30:13Z"
    mac: ENC[AES256_GCM,data:iVpwBpoRiu+HAhZgOQeFK1HHlaWLiNxMRsWBjMXM+JiKUmSHeYR1nIQU3AGUHfq6HYxp83N6zbSRG/yHuF83WypFjOPf9NqG44mDJf+ecZua/WPcaHRWkBQA0/5rPFWMKy6aFrXTWPdMxKJLxhiJ8DvJg2UjCW2hd2F4JO7BhgQ=,iv:OXTHxj4X4bIN4PjH0m2/vj80IJoePkZTV2CFhJ7rVdw=,tag:g++xfi1QAxzfRHhyKVOHgw==,type:str]
    version: 3.13.3
