apiVersion: v1
data:
    key: ENC[AES256_GCM,data:He9f1fq0ACsBsGG1LcujnvQmXTs+gvhp1z+Hww5chU/HcFOqxZ12QPuhHwEXze2aQO4OmNK0/IS6dSCH,iv:7I6yFYFL7WAdohjzW5b4IZa49upYH+/inqP0xd72awE=,tag:7YVxK3uHyVMf5cAv9qnQ0g==,type:str]
kind: Secret
metadata:
    labels:
        app.kubernetes.io/instance: mastodon
        app.kubernetes.io/name: welcome-access
    name: welcome-access
    namespace: mastodon
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsS251WWJ3aXRaeHNodHV4
            eUpXSy9Eeksxa1pvZDByaHRNZ3FBSmg4RVUwCllON2xFVXM1RTFOUlJrVU9TSEVj
            amxLMWJPQ3JUTmF4UWZXZWU5Ym1WcXMKLS0tIEY5MTRXMGdvcTNvT3FoQ1RqR3V1
            NStDeVJ6MVBmdUl1cGJEOGlqTUtyUFkKj9mj1HDC9DLm6G0XHaB3PysbvBS8QjJB
            RV1YfKM+vgzZHXvVoBnkaFSePv3F1W2DBKbv5BoymrT5nucUDm8wfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qky2jy0fqdputaryf4s57jt8x8cnwrc4cxnuzrgggd8p5vxxhytqkt8g8s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T03:30:45Z"
    mac: ENC[AES256_GCM,data:sazoMEYGiClb+5pW27FGWNRiBT+p2WrwfNZ+hB9vbF3MAMrW6Sz+u92lulrIhmcpuv1O69VmQ1n0zJeUcRZT/1MPC/blirH2pie0PmZkR0IsTobY67PyAwkvRFulupS/JYoTSHFNzUj99ssRfHWtucT7zJx2bepLGrfwMjMEgMs=,iv:pBSPAhRunWpf8LwaVo473wlR/80AxRjP0ytOae0Mk6c=,tag:T7qH3t2tp+rWacFE+yWd7w==,type:str]
    version: 3.13.3
