apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-redis
  namespace: mastodon
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
      nbthread 4
      cpu-map auto:1/1-4 0-3

    defaults
     log global
     timeout connect 5s
     timeout client 1m
     timeout server 1m

    # https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#5.3
    resolvers kube-dns
      parse-resolv-conf
      resolve_retries    30
      timeout retry      1s
      hold valid         1s

    frontend redis
      bind :6379
      default_backend upstream_redis
      mode tcp

    backend upstream_redis
      server upstream_redis "$REDIS_HOST":"$REDIS_PORT" ssl verify none check inter 1s resolvers kube-dns
      mode tcp
      balance roundrobin