apiVersion: apps/v1
kind: Deployment
metadata:
  name: page-replica
  namespace: mastodon
  labels:
    app: page-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: page-replica
  template:
    metadata:
      labels:
        app: page-replica
    spec:
      containers:
        - name: page-replica
          image: ghcr.io/five-borough-fedi-project/masto.nyc-docean/page-replica:0c053d6bec1ab7430a5cf572bef6af954bf4996d
          ports:
            - containerPort: 8080
          env:
            - name: BASE_URL
              value: "https://masto.nyc"
            - name: REMOVE_JS
              value: "true"
            - name: ADD_BASE_URL
              value: "true"
            - name: CACHE_FOLDER
              value: "/tmp/page-replica"
            - name: RESTRICT_TO_BASE_URL
              value: "true"
