apiVersion: apps/v1
kind: Deployment
metadata:
  name: libretranslate
  namespace: mastodon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: libretranslate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: libretranslate
    spec:
      containers:
      - name: libretranslate
        image: docker.io/libretranslate/libretranslate:v1.6.0
        ports:
        - containerPort: 5000
        env:
        - name: "LT_HOST"
          value: "0.0.0.0"
        - name: "LT_UPDATE_MODELS"
          value: "true"
        - name: "LT_DISABLE_WEB_UI"
          value: "true"
