apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-nginx
  namespace: mastodon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      volumes:
        - name: masto-nginx-config
          configMap:
            name: masto-nginx-config-prd
      containers:
        - name: mastodon-nginx
          image: docker.io/nginx:1.29.1-alpine-slim
          ports:
          - containerPort: 80
            name: http
          volumeMounts:
            - name: masto-nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
