---
# Source: mastodon/templates/deployment-sidekiq.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stunnel
  labels:
    app.kubernetes.io/name: stunnel
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stunnel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stunnel
    spec:
      containers:
        - name: stunnel
          image: dweomer/stunnel
          imagePullPolicy: IfNotPresent
          env:
            - name: STUNNEL_SERVICE
              value: "redis"
            - name: STUNNEL_ACCEPT
              value: "6379"
            - name: STUNNEL_CLIENT
              value: "yes"
            - name: STUNNEL_CONNECT
              valueFrom:
                secretKeyRef:
                  name: masto-redis
                  key: private_host_and_port
            
