# Supporting workloads: both cloudflared tunnels, nginx, libretranslate and
# the welcome webhook.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mastodon
resources:
  - cloudflared-small.yaml
  - cloudflared.yaml
  - configmap-cloudflared-small.yaml
  - configmap-cloudflared.yaml
  - configmap-nginx.yaml
  - deployment-libretranslate.yaml
  - deployment-nginx.yaml
  - webhook-welcome.yaml
