apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-webhook
  namespace: mastodon
spec:
  selector:
    matchLabels:
      app: welcome-webhook
  template:
    metadata:
      labels:
        app: welcome-webhook
    spec:
      containers:
      - name: welcome-webhook
        # TODO: can the image be terraform-ed or put somewhere else, like github?
        image: ghcr.io/five-borough-fedi-project/masto.nyc-docean/welcome-bot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: "WELCOMEACCESSTOKEN"
          valueFrom:
            secretKeyRef:
              name: welcome-access
              key: key