apiVersion: v1
kind: Service
metadata:
  name: haproxy-redis
  namespace: mastodon
  labels:
    app.kubernetes.io/name: haproxy-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: haproxy-redis