---
# Source: mastodon/templates/service-streaming.yaml
apiVersion: v1
kind: Service
metadata:
  name: stunnel
  labels:
    app.kubernetes.io/name: stunnel
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: stunnel
  selector:
    app.kubernetes.io/name: stunnel
