name: Build and push Docker images to GitHub Container Registry

on:
  push:
    paths:
      - '**.py'
      - '**.js'
      - '**.ts'
      - '**.json'
      - '**.Dockerfile'
      - 'docker/**'
      - '.github/workflows/docker_images.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          # Find all Dockerfiles in /docker/*/Dockerfile
          - ${{ fromJson(steps.find_dockerfiles.outputs.matrix) }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Find Dockerfiles
        id: find_dockerfiles
        run: |
          files=$(find ./docker -mindepth 2 -maxdepth 2 -name Dockerfile | jq -R . | jq -s .)
          echo "matrix=$files" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ${{ dirname(matrix.dockerfile) }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/masto.nyc-docean/${{ basename(dirname(matrix.dockerfile)) }}:latest
            ghcr.io/${{ github.repository_owner }}/masto.nyc-docean/${{ basename(dirname(matrix.dockerfile)) }}:${{ github.sha }}